logging.level:
  io.billkoch: trace
  org.flywaydb: info
  org.springframework.cloud: trace
  org.springframework.vault: trace

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
  jpa.hibernate.ddl-auto: validate

---
spring:
  profiles: integration-test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:5.7.17://localhost/test
