logging.level:
  org.flywaydb: trace
  org.springframework.cloud.vault: trace

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
  jpa.hibernate.ddl-auto: validate

---
spring:
  profiles: integration-test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:9.6.2-alpine://localhost/test
